/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: pixel                                                 *
* Dimensions:  4 * 4                                                 *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmpixel;

static GUI_CONST_STORAGE unsigned long _acpixel[] = {
  0x27BC3851, 0xFFFFFFFF, 0xEA000000, 0x02000000,
  0xF9BC3851, 0xFFFFFFFF, 0xFFFFFFFF, 0xF8000000,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xEE000000,
  0x3D000000, 0xDC000000, 0xFFFFFFFF, 0x52000000
};

GUI_CONST_STORAGE GUI_BITMAP bmpixel = {
  4, // xSize
  4, // ySize
  16, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acpixel,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
